name: Build and Push Solr Docker Image

on:
  push:
    branches:
      - main
    paths:
      - solr/Dockerfile
    tags:
      - 'solr@v?[0-9]+.[0-9]+.[0-9]+'

  workflow_dispatch:

env:
  SOLR_SERVER_CORE_URL: https://maven.xwiki.org/releases/org/xwiki/platform/xwiki-platform-search-solr-server-core/15.5/xwiki-platform-search-solr-server-core-15.5.jar
  SOLR_CORE_MINIMAL_URL: https://maven.xwiki.org/releases/org/xwiki/platform/xwiki-platform-search-solr-server-core-minimal/15.5/xwiki-platform-search-solr-server-core-minimal-15.5.zip
  ARCHIVE_PATH: solr/config/solr

jobs:
  build_push:
    
    name: Build and push Solr Docker image
    runs-on: ubuntu-latest     
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
            fetch-depth: 0
            sparse-checkout: |
              solr

      - name: Extract version tag from github.ref_name
        id: extract_version
        run: |
          if [[ "${{ github.ref_name }}" =~ solr@v?([0-9]+\.[0-9]+\.[0-9]+) ]]; then
            echo "VERSION_TAG=${BASH_REMATCH[1]}" >> "$GITHUB_ENV"
          else
            echo "Invalid version tag format. Skipping image push."
            exit 1
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
                

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}   

      - name: Lowercase the repository owner username
        run: |
          echo REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]') >> "$GITHUB_ENV"   

      - name: Build and push images
        uses: docker/build-push-action@v4
        with:
          context: ./solr
          file: ./solr/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/solr:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/solr:${{ env.VERSION_TAG  }}
            ghcr.io/${{ env.REPO_OWNER }}/solr:latest
            ghcr.io/${{ env.REPO_OWNER }}/solr:${{ env.VERSION_TAG  }}
